name = "Star-Field-Client_Full"
author = "ManyStars"
version = "1.0.0.0-beta.2+26A2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd8d29019952b207b2a96ce61a0cecc351f7d08f2f3c6a5018ef9cca180a4369"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
