name = "Star-Field-Client_Full"
author = "ManyStars"
version = "1.0.0.0-beta.3+26A3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56337e3a2ecc6f9cb3d4ca2a6a1ba966090a0474b52474646d177104ee76307a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
