name = "Star-Field-Client_Full"
author = "ManyStars"
version = "1.0.0.0-rc.1+26A15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa0d26adc93219ac916a719e1131d3d5ec70f8e85d98a31b2bdb064c5199aadd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
